name: Deploy to Linux Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 22

            - name: Install deps
              run: npm install

            - name: Build project
              run: npm run build

            - name: Export static files (Next.js)
              run: npm run export

            # FIX SSH VERIFICATION ISSUE HERE
            - name: Add known hosts
              run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

            - name: Upload to server
              run: |
                  scp -r -P ${{ secrets.SERVER_PORT }} ./out/* \
                    ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/***/htdocs/brandstar.space
